export const dataSources = [
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@akvo.com",
    email_verified: "16-12-2020 at 12:06",
    organisation: "Staff Akvo",
    role: "Admin",
    access: "Surveys",
    info: "info",
  },
  {
    id: 2,
    name: "John Doe",
    email: "johndoe@mail.com",
    email_verified: "16-12-2020 at 12:06",
    organisation: "Organisation",
    role: "Role",
    access: "Surveys",
    info: null,
  },
  {
    id: 3,
    name: "John Doe",
    email: "johndoe@mail.com",
    email_verified: "16-12-2020 at 12:06",
    organisation: "Organisation",
    role: "Role",
    access: "Surveys",
    info: null,
  },
  {
    id: 4,
    name: "John Doe",
    email: "johndoe@mail.com",
    email_verified: "16-12-2020 at 12:06",
    organisation: "Organisation",
    role: "Role",
    access: "Surveys",
    info: null,
  },
  {
    id: 5,
    name: "John Doe",
    email: "johndoe@mail.com",
    email_verified: "16-12-2020 at 12:06",
    organisation: "Organisation",
    role: "Role",
    access: "Surveys",
    info: null,
  },
  {
    id: 6,
    name: "John Doe",
    email: "johndoe@mail.com",
    email_verified: "16-12-2020 at 12:06",
    organisation: "Organisation",
    role: "Role",
    access: "Surveys",
    info: null,
  },
  {
    id: 7,
    name: "John Doe",
    email: "johndoe@mail.com",
    email_verified: "16-12-2020 at 12:06",
    organisation: "Organisation",
    role: "Role",
    access: "Surveys",
    info: null,
  },
  {
    id: 8,
    name: "John Doe",
    email: "johndoe@mail.com",
    email_verified: "16-12-2020 at 12:06",
    organisation: "Organisation",
    role: "Role",
    access: "Surveys",
    info: null,
  },
];
