version: "3"
services:
  backend:
   image: akvo/akvo-lumen-backend-dev:20200610.033159.f413ba3
   expose:
     - 3000
   volumes:
      - ./flow-to-rsr:/app
      - ~/.m2:/home/akvo/.m2
      - ~/.lein:/home/akvo/.lein
      - ~/.m2:/root/.m2:delegated
      - ~/.lein:/root/.lein:delegated
   ports:
      - "47480:47480"
      - "3000:3000"
   command: ["./run.sh"]
