---
version: "3"
services:
  mainnetwork:
    image: alpine:3.14.0
    command: ["tail", "-f", "/dev/null"]
    ports:
      - 5000:5000
  db:
    command: "postgres -c 'shared_buffers=128MB' -c 'fsync=off' -c 'synchronous_commit=off' -c 'full_page_writes=off' -c 'max_connections=100' -c 'bgwriter_lru_maxpages=0' -c 'client_min_messages=warning'"
    restart: always
  frontend:
    image: eu.gcr.io/akvo-lumen/isco/frontend:latest
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - backend
      - db
  backend:
    image: eu.gcr.io/akvo-lumen/isco/backend:latest
    command: ["sh", "./e2e.sh"]
    environment:
      - DATABASE_URL=postgresql://isco_user:password@db:5432/isco
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/isco-service-account.json
      - SECRET_KEY=36ca26dbc9f6a435aa7ad404491d1650cd9485eef9ca8ea60501495b0526d4df
      - WEBDOMAIN=http://localhost
      - MAILJET_SECRET=notset
      - MAILJET_APIKEY=notset
    depends_on:
      - db
    restart: always
    volumes:
      - ./backend:/app:delegated
      - ${SERVICE_ACCOUNT}:/credentials/:ro
    network_mode: service:mainnetwork
  chromedriver:
    image: selenium/standalone-chrome
    restart: always
    network_mode: service:mainnetwork
  selenium:
    image: akvo/akvo-selenium-side-runner:20230215.031651.e73d03e
    entrypoint: ./entrypoint.sh
    working_dir: /app
    environment:
      - MAILJET_VERIFICATION_FILE
    volumes:
      - ./tests:/app
    network_mode: service:mainnetwork
    depends_on:
      - db
      - backend
      - frontend
      - chromedriver
