---
version: "3"
services:
  backend:
    command: ["sh", "./e2e.sh"]
  chromedriver:
    image: selenium/standalone-chrome
    restart: always
    network_mode: service:mainnetwork
    depends_on:
      - frontend
  selenium:
    image: akvo/akvo-selenium-side-runner:20230215.031651.e73d03e
    command: ["./run.sh"]
    working_dir: /app
    volumes:
      - ./tests:/app
    network_mode: service:mainnetwork
    depends_on:
      - frontend
      - chromedriver
