---
version: "3"
services:
  mainnetwork:
    image: alpine:3.14.0
    command: ["tail", "-f", "/dev/null"]
    ports:
      - 3000:3000
      - 5000:5000
      - 4444:4444
  db:
    command: "postgres -c 'shared_buffers=128MB' -c 'fsync=off' -c 'synchronous_commit=off' -c 'full_page_writes=off' -c 'max_connections=100' -c 'bgwriter_lru_maxpages=0' -c 'client_min_messages=warning'"
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
      - ./db/script:/script:ro
    restart: always
  backend:
    image: eu.gcr.io/akvo-lumen/isco/backend:latest
    volumes:
      - ./:/app:delegated
      - ${SERVICE_ACCOUNT}:/credentials/:ro
    working_dir: /app/backend
    command: tail -f /dev/null
    environment:
      - DATABASE_URL=postgresql://isco_user:password@db:5432/isco
      - SECRET_KEY=36ca26dbc9f6a435aa7ad404491d1650cd9485eef9ca8ea60501495b0526d4df
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/isco-service-account.json
      - WEBDOMAIN=notset
      - COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN:-}
      - SEMAPHORE=${SEMAPHORE:-}
      - SEMAPHORE_JOB_ID=${SEMAPHORE_JOB_ID:-}
      - SEMAPHORE_WORKFLOW_ID=${SEMAPHORE_WORKFLOW_ID:-}
      - SEMAPHORE_GIT_PR_NUMBER=${SEMAPHORE_GIT_PR_NUMBER:-}
      - SKIP_MIGRATION=yes
      - BUCKET_FOLDER=local
      - CLIENT_ID=test
      - CLIENT_SECRET=test
      - MAILJET_SECRET=notset
      - MAILJET_APIKEY=notset
    depends_on:
      - db
    network_mode: service:mainnetwork
  frontend:
    image: eu.gcr.io/akvo-lumen/isco/frontend:latest
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - backend
      - db
    network_mode: service:mainnetwork
  chromedriver:
    image: selenium/standalone-chrome
    restart: always
    network_mode: service:mainnetwork
    depends_on:
      - frontend
  selenium:
    image: akvo/akvo-selenium-side-runner:20230215.031651.e73d03e
    command: ["./run.sh"]
    working_dir: /app
    volumes:
      - ./tests:/app
    network_mode: service:mainnetwork
    depends_on:
      - frontend
      - chromedriver
volumes:
  pg-data:
