---
version: "3"
services:
  backend:
    command: ["sh", "./e2e.sh"]
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/isco-service-account.json
      - SECRET_KEY=36ca26dbc9f6a435aa7ad404491d1650cd9485eef9ca8ea60501495b0526d4df
      - WEBDOMAIN=http://localhost:3000
      - MAILJET_SECRET=notset
      - MAILJET_APIKEY=notset
  chromedriver:
    image: selenium/standalone-chrome
    restart: always
    network_mode: service:mainnetwork
    depends_on:
      - db
      - backend
      - frontend
  selenium:
    image: akvo/akvo-selenium-side-runner:20230215.031651.e73d03e
    command: ["tail", "-f", "/dev/null"]
    working_dir: /app
    volumes:
      - ./tests:/app
    network_mode: service:mainnetwork
    depends_on:
      - db
      - backend
      - frontend
      - chromedriver
