---
version: "3.9"
services:
  mainnetwork:
    ports:
      - 3000:3000
      - 5000:5000
      - 5050:5050
  chromedriver:
    image: selenium/standalone-chrome
    restart: always
    network_mode: service:mainnetwork
  selenium:
    image: akvo/akvo-selenium-side-runner:20230215.031651.e73d03e
    command: ["tail", "-f", "/dev/null"]
    working_dir: /app
    volumes:
      - ./tests:/app
    network_mode: service:mainnetwork
  pgadmin:
    image: dpage/pgadmin4:5.7
    environment:
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_DEFAULT_EMAIL=dev@akvo.org
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
      - pg-admin-data:/var/lib/pgadmin
    depends_on:
      - db
    network_mode: service:mainnetwork
  backend:
    volumes:
      - ./backend:/app:delegated
      - ../akvo-config/k8s-secrets/test/isco:/credentials/:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/isco-service-account.json
      - WEBDOMAIN=http://localhost:3000
      - MAILJET_SECRET=$MAILJET_SECRET
      - MAILJET_APIKEY=$MAILJET_APIKEY
volumes:
  pg-admin-data:
