---
version: "3"
services:
  mainnetwork:
    image: alpine:3.14.0
    command: ["tail", "-f", "/dev/null"]
    ports:
      - 3000:3000
      - 5000:5000
  db:
    command: "postgres -c 'shared_buffers=128MB' -c 'fsync=off' -c 'synchronous_commit=off' -c 'full_page_writes=off' -c 'max_connections=100' -c 'bgwriter_lru_maxpages=0' -c 'client_min_messages=warning'"
    restart: always
  frontend:
    image: eu.gcr.io/akvo-lumen/isco/frontend:latest
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - backend
      - db
  backend:
    image: eu.gcr.io/akvo-lumen/isco/backend:latest
    network_mode: service:mainnetwork
    command: ["sh", "run.sh"]
    environment:
      - DATABASE_URL=postgresql://isco_user:password@db:5432/isco
      - SECRET_KEY=36ca26dbc9f6a435aa7ad404491d1650cd9485eef9ca8ea60501495b0526d4df
      - SKIP_MIGRATION=yes
      - WEBDOMAIN=notset
      - MAILJET_SECRET=notset
      - MAILJET_APIKEY=notset
    depends_on:
      - db
    restart: always
    volumes:
      - ./backend:/app:delegated
      - ${SERVICE_ACCOUNT}:/credentials/:ro
  ci:
    image: alpine:3.14
    network_mode: service:mainnetwork
    volumes:
      - ./ci/test:/test:ro
    working_dir: /test
    entrypoint: ./entrypoint.sh
    environment:
      - MAILJET_VERIFICATION_FILE
    depends_on:
      - db
      - backend
      - frontend
