# list of member survey id
MEMBER_SURVEY = [1, 7]
# list of project survey id
PROJECT_SURVEY = [2, 4, 5, 6, 8]


# MEMBER TYPE UNLIMITED MEMBER SURVEY
# 4 : DISCO - Traders
MEMBER_SURVEY_UNLIMITED_MEMBER = [4]

# ISCO TYPE UNLIMITED MEMBER SURVEY
# 3 : DISCO
MEMBER_SURVEY_UNLIMITED_ISCO = [3]
