export { default as Home } from "./home/Home";
export { default as Admin } from "./admin/Admin";
export { default as ManageSurvey } from "./manage-survey/ManageSurvey";
export { default as ManageUser } from "./manage-user/ManageUser";
export { default as SurveyEditor } from "./survey-editor/SurveyEditor";
export { default as Login } from "./auth/Login";
export { default as Register } from "./auth/Register";
export { default as Invitation } from "./auth/Invitation";
export { default as ErrorPage } from "./error/ErrorPage";
// export { default as WebformPage } from "./survey/WebformPage";
export { default as Survey } from "./survey/Survey";
